spring:
  datasource:
    url: jdbc:mysql://solutionfrienddb.cxuwucgcsxaw.ap-northeast-2.rds.amazonaws.com:3306/Solution_friendDB
    username: root
    password: Gomin5!!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true